packages: []

audit:
  ignorePrune: true

autoDedupe: true

catalog:
  '@mestriga-org/eslint-config': github:mestriga-org/eslint-config#83dd747c4b8e184da820dcbe04c5e4b124faba77
  eslint: 10.11.0
catalogMode: strict

catalogPrune: true
dedupeDirectDeps: true
dedupePeers: true
disallowWorkspaceCycles: true
enablePrePostScripts: false
hoist: false
minimumReleaseAgeExcludePrune: true

nodeOptions: >-
  ${NODE_OPTIONS- }
  --no-addons
  --disable-proto=delete
  --force-context-aware
  --force-node-api-uncaught-exceptions-policy
  --frozen-intrinsics
  --no-global-search-paths
  --pending-deprecation
  --tls-min-v1.3

resolutionMode: lowest-direct
strictPeerDependencies: true
trustPolicyExcludePrune: true
