# This workflow is managed by gh actions-lock.

name: CI
on:
  merge_group:
    branches: [main]
  pull_request:
    branches: [main]
  push:
    branches: [main]
permissions: { }
jobs:
  git-check:
    permissions:
      contents: read
    uses: mestriga-org/public-workflows/.github/workflows/git-check.yml@main
