# This workflow is managed by gh actions-lock.

on:
  merge_group:
  pull_request:
  push:
    branches: [main]
permissions: { }
jobs:
  workflow-lint:
    permissions:
      contents: read
    uses: mestriga-org/public-workflows/.github/workflows/workflow-lint.yml@main
